apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: github-service
  title: Create GitHub Service
  description: Creates a repo in GitHub

spec:
  owner: platform-team
  type: service

  parameters:
    - title: Service Details
      required:
        - name
      properties:
        name:
          title: Service Name
          type: string
        repoOwner:
          title: GitHub Org/User
          type: string
          default: saston2003

  steps:
    - id: fetch
      name: Fetch Template
      action: fetch:template
      input:
        url: ./template
        values:
          name: ${{ parameters.name }}
          owner: platform-team

    - id: publish
      name: Create GitHub repo
      action: publish:github
      input:
        description: Service created via Backstage
        repoVisibility: private
        repoUrl: github.com?owner=${{ parameters.repoOwner }}&repo=${{ parameters.name }}
        defaultBranch: main

    - id: register
      name: Register in catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml